#!/bin/bash
sudo apt update -y
sudo apt install curl -y
sudo apt install nodejs -y
sudo apt install git -y
sudo apt install npm -y
git clone https://github.com/Vampire-Offical/awsworkshop.git
cd awsworkshop
npm i
sudo npm install -g pm2
sudo pm2 start --name 'awsworkshop' install.js